"""Ported 1:1 from the frontend's src/data/mockAttractions.ts (same ids,
same durations/costs/travel estimates), so itineraries generated here look
identical to what the frontend's own mock generator would have produced.
"""

MOCK_ATTRACTIONS: list[dict] = [
    # ---------------- Hyderabad ----------------
    {"id": "hyd-charminar", "destination_id": "hyderabad", "name": "Charminar", "categories": ["history", "photography"], "description": "The 16th-century icon of the old city, with bustling bazaars at its feet.", "duration_minutes": 90, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 12, "distance_km_to_next": 3, "best_slot": "morning"},
    {"id": "hyd-chowmahalla", "destination_id": "hyderabad", "name": "Chowmahalla Palace", "categories": ["history"], "description": "The opulent seat of the Nizams, with grand courtyards and chandeliers.", "duration_minutes": 90, "cost": 100, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 4, "best_slot": "morning"},
    {"id": "hyd-food-street", "destination_id": "hyderabad", "name": "Local Food Experience", "categories": ["food"], "description": "A guided tasting trail through Hyderabadi biryani, haleem and Irani chai spots.", "duration_minutes": 60, "cost": 300, "scene_type": "city", "travel_minutes_to_next": 18, "distance_km_to_next": 6, "best_slot": "afternoon"},
    {"id": "hyd-salarjung", "destination_id": "hyderabad", "name": "Salar Jung Museum", "categories": ["history", "photography"], "description": "One of the largest one-man art collections in the world.", "duration_minutes": 120, "cost": 100, "scene_type": "heritage", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "afternoon"},
    {"id": "hyd-golconda", "destination_id": "hyderabad", "name": "Golconda Fort", "categories": ["history", "adventure", "photography"], "description": "A hilltop fortress famous for its acoustics and sound-and-light show.", "duration_minutes": 120, "cost": 150, "scene_type": "heritage", "travel_minutes_to_next": 25, "distance_km_to_next": 9, "best_slot": "evening"},
    {"id": "hyd-laadbazaar", "destination_id": "hyderabad", "name": "Laad Bazaar", "categories": ["shopping", "photography"], "description": "A glittering lane famous for bangles, pearls and old-city charm.", "duration_minutes": 60, "cost": 200, "scene_type": "city", "travel_minutes_to_next": 10, "distance_km_to_next": 2, "best_slot": "afternoon"},
    {"id": "hyd-hussainsagar", "destination_id": "hyderabad", "name": "Hussain Sagar & Necklace Road", "categories": ["nature", "photography"], "description": "A sunset walk beside the lake and its monolithic Buddha statue.", "duration_minutes": 75, "cost": 0, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},
    {"id": "hyd-ramoji", "destination_id": "hyderabad", "name": "Ramoji Film City", "categories": ["entertainment"], "description": "One of the world's largest film studio complexes, open for tours.", "duration_minutes": 240, "cost": 1200, "scene_type": "city", "travel_minutes_to_next": 30, "distance_km_to_next": 12, "best_slot": "morning"},

    # ---------------- Araku Valley ----------------
    {"id": "ark-train", "destination_id": "araku-valley", "name": "Visakhapatnam – Araku Scenic Train", "categories": ["nature", "photography"], "description": "A 4-hour heritage rail journey through 58 tunnels and misty hills.", "duration_minutes": 240, "cost": 300, "scene_type": "hills", "travel_minutes_to_next": 10, "distance_km_to_next": 4, "best_slot": "morning"},
    {"id": "ark-borra", "destination_id": "araku-valley", "name": "Borra Caves", "categories": ["nature", "adventure", "photography"], "description": "Million-year-old limestone caves with dramatic stalactite formations.", "duration_minutes": 90, "cost": 90, "scene_type": "hills", "travel_minutes_to_next": 35, "distance_km_to_next": 15, "best_slot": "morning"},
    {"id": "ark-waterfalls", "destination_id": "araku-valley", "name": "Chaparai Waterfalls", "categories": ["nature", "adventure"], "description": "Wide rock-bed cascades where you can wade in shallow pools.", "duration_minutes": 90, "cost": 30, "scene_type": "hills", "travel_minutes_to_next": 25, "distance_km_to_next": 10, "best_slot": "afternoon"},
    {"id": "ark-museum", "destination_id": "araku-valley", "name": "Tribal Museum", "categories": ["history", "photography"], "description": "Life-size dioramas of the region's indigenous tribal cultures.", "duration_minutes": 60, "cost": 20, "scene_type": "hills", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "afternoon"},
    {"id": "ark-coffee", "destination_id": "araku-valley", "name": "Coffee Plantation Visit", "categories": ["nature", "food"], "description": "A guided walk and tasting through Araku's organic coffee estates.", "duration_minutes": 90, "cost": 150, "scene_type": "hills", "travel_minutes_to_next": 20, "distance_km_to_next": 6, "best_slot": "afternoon"},
    {"id": "ark-viewpoint", "destination_id": "araku-valley", "name": "Araku Valley Viewpoint", "categories": ["nature", "photography"], "description": "Layered ridgelines and coffee valleys, best at sunrise or sunset.", "duration_minutes": 45, "cost": 0, "scene_type": "hills", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "evening"},
    {"id": "ark-market", "destination_id": "araku-valley", "name": "Local Handicrafts Market", "categories": ["shopping", "food"], "description": "Bamboo crafts, tribal jewellery and fresh local produce.", "duration_minutes": 60, "cost": 200, "scene_type": "hills", "travel_minutes_to_next": 10, "distance_km_to_next": 3, "best_slot": "evening"},

    # ---------------- Hampi ----------------
    {"id": "ham-virupaksha", "destination_id": "hampi", "name": "Virupaksha Temple", "categories": ["history", "spiritual", "photography"], "description": "A still-active 7th-century temple with a soaring gopuram.", "duration_minutes": 60, "cost": 0, "scene_type": "temple", "travel_minutes_to_next": 10, "distance_km_to_next": 3, "best_slot": "morning"},
    {"id": "ham-vittala", "destination_id": "hampi", "name": "Vittala Temple & Stone Chariot", "categories": ["history", "photography"], "description": "Hampi's architectural showpiece, with its iconic musical pillars.", "duration_minutes": 90, "cost": 40, "scene_type": "heritage", "travel_minutes_to_next": 20, "distance_km_to_next": 6, "best_slot": "morning"},
    {"id": "ham-matanga", "destination_id": "hampi", "name": "Matanga Hill Sunrise", "categories": ["adventure", "photography", "nature"], "description": "A short boulder climb rewarded with Hampi's best panoramic view.", "duration_minutes": 90, "cost": 0, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 4, "best_slot": "morning"},
    {"id": "ham-royal", "destination_id": "hampi", "name": "Royal Enclosure & Lotus Mahal", "categories": ["history"], "description": "The ceremonial heart of the Vijayanagara empire.", "duration_minutes": 90, "cost": 40, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "afternoon"},
    {"id": "ham-tungabhadra", "destination_id": "hampi", "name": "Tungabhadra River Coracle Ride", "categories": ["adventure", "nature"], "description": "A traditional round-boat ride past riverside ruins.", "duration_minutes": 45, "cost": 200, "scene_type": "heritage", "travel_minutes_to_next": 12, "distance_km_to_next": 3, "best_slot": "afternoon"},
    {"id": "ham-food", "destination_id": "hampi", "name": "Hampi Bazaar Food Walk", "categories": ["food"], "description": "Local thalis and cafes overlooking the temple bazaar.", "duration_minutes": 60, "cost": 250, "scene_type": "heritage", "travel_minutes_to_next": 10, "distance_km_to_next": 2, "best_slot": "evening"},

    # ---------------- Kerala ----------------
    {"id": "ker-houseboat", "destination_id": "kerala", "name": "Alleppey Houseboat Cruise", "categories": ["nature", "photography"], "description": "An overnight cruise through the palm-lined backwaters.", "duration_minutes": 300, "cost": 3500, "scene_type": "backwaters", "travel_minutes_to_next": 20, "distance_km_to_next": 8, "best_slot": "morning"},
    {"id": "ker-fortkochi", "destination_id": "kerala", "name": "Fort Kochi Heritage Walk", "categories": ["history", "photography"], "description": "Chinese fishing nets, colonial churches and street art.", "duration_minutes": 120, "cost": 100, "scene_type": "heritage", "travel_minutes_to_next": 25, "distance_km_to_next": 10, "best_slot": "morning"},
    {"id": "ker-spice", "destination_id": "kerala", "name": "Spice Plantation Tour, Thekkady", "categories": ["nature", "food"], "description": "Guided walks through cardamom, pepper and clove estates.", "duration_minutes": 120, "cost": 400, "scene_type": "hills", "travel_minutes_to_next": 30, "distance_km_to_next": 12, "best_slot": "afternoon"},
    {"id": "ker-kathakali", "destination_id": "kerala", "name": "Kathakali Dance Performance", "categories": ["entertainment", "history"], "description": "A live classical dance-drama with elaborate make-up and costume.", "duration_minutes": 90, "cost": 350, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},
    {"id": "ker-beach", "destination_id": "kerala", "name": "Varkala Cliff Beach", "categories": ["nature", "adventure"], "description": "Dramatic red cliffs overlooking the Arabian Sea.", "duration_minutes": 150, "cost": 0, "scene_type": "beach", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "evening"},
    {"id": "ker-seafood", "destination_id": "kerala", "name": "Backwater Seafood Dinner", "categories": ["food"], "description": "Fresh Keralan seafood cooked in coconut and curry leaf.", "duration_minutes": 75, "cost": 500, "scene_type": "backwaters", "travel_minutes_to_next": 10, "distance_km_to_next": 3, "best_slot": "evening"},

    # ---------------- Ladakh ----------------
    {"id": "lad-pangong", "destination_id": "ladakh", "name": "Pangong Tso Lake", "categories": ["nature", "photography", "adventure"], "description": "A shape-shifting turquoise lake at 4,225m, straddling the India-China border.", "duration_minutes": 240, "cost": 500, "scene_type": "mountain", "travel_minutes_to_next": 40, "distance_km_to_next": 30, "best_slot": "morning"},
    {"id": "lad-khardungla", "destination_id": "ladakh", "name": "Khardung La Pass", "categories": ["adventure", "photography"], "description": "One of the world's highest motorable passes.", "duration_minutes": 90, "cost": 100, "scene_type": "mountain", "travel_minutes_to_next": 35, "distance_km_to_next": 25, "best_slot": "morning"},
    {"id": "lad-thiksey", "destination_id": "ladakh", "name": "Thiksey Monastery", "categories": ["spiritual", "history", "photography"], "description": "A striking 12-storey monastery resembling Lhasa's Potala Palace.", "duration_minutes": 90, "cost": 30, "scene_type": "mountain", "travel_minutes_to_next": 20, "distance_km_to_next": 12, "best_slot": "afternoon"},
    {"id": "lad-leh-market", "destination_id": "ladakh", "name": "Leh Main Bazaar", "categories": ["shopping", "food"], "description": "Pashmina, Tibetan crafts and Ladakhi street food.", "duration_minutes": 90, "cost": 400, "scene_type": "mountain", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},
    {"id": "lad-nubra", "destination_id": "ladakh", "name": "Nubra Valley & Sand Dunes", "categories": ["nature", "adventure"], "description": "Double-humped Bactrian camels against cold-desert dunes.", "duration_minutes": 180, "cost": 600, "scene_type": "desert", "travel_minutes_to_next": 45, "distance_km_to_next": 35, "best_slot": "afternoon"},

    # ---------------- Madurai ----------------
    {"id": "mdu-meenakshi", "destination_id": "madurai", "name": "Meenakshi Amman Temple", "categories": ["spiritual", "history", "photography"], "description": "A dazzling 14-gopuram temple complex, the soul of Madurai.", "duration_minutes": 120, "cost": 50, "scene_type": "temple", "travel_minutes_to_next": 12, "distance_km_to_next": 3, "best_slot": "morning"},
    {"id": "mdu-palace", "destination_id": "madurai", "name": "Thirumalai Nayak Palace", "categories": ["history", "photography"], "description": "A 17th-century Indo-Saracenic palace with a grand courtyard.", "duration_minutes": 60, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 4, "best_slot": "morning"},
    {"id": "mdu-market", "destination_id": "madurai", "name": "Puthu Mandapam Market", "categories": ["shopping", "food"], "description": "A pillared 16th-century hall now packed with tailors and flower vendors.", "duration_minutes": 60, "cost": 200, "scene_type": "temple", "travel_minutes_to_next": 10, "distance_km_to_next": 2, "best_slot": "afternoon"},
    {"id": "mdu-food", "destination_id": "madurai", "name": "Jigarthanda & Local Food Trail", "categories": ["food"], "description": "Madurai's famous cooling drink plus mutton chukka and idiyappam.", "duration_minutes": 60, "cost": 250, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "afternoon"},
    {"id": "mdu-gandhi", "destination_id": "madurai", "name": "Gandhi Memorial Museum", "categories": ["history"], "description": "A moving account of the independence movement, housed in a former palace.", "duration_minutes": 75, "cost": 0, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},

    # ---------------- Goa ----------------
    {"id": "goa-baga", "destination_id": "goa", "name": "Baga & Calangute Beach", "categories": ["nature", "entertainment"], "description": "Golden sands, water sports and Goa's liveliest beach shacks.", "duration_minutes": 150, "cost": 300, "scene_type": "beach", "travel_minutes_to_next": 15, "distance_km_to_next": 6, "best_slot": "morning"},
    {"id": "goa-fort", "destination_id": "goa", "name": "Fort Aguada & Candolim", "categories": ["history", "photography"], "description": "A 17th-century Portuguese fort overlooking the Arabian Sea.", "duration_minutes": 75, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 20, "distance_km_to_next": 8, "best_slot": "afternoon"},
    {"id": "goa-market", "destination_id": "goa", "name": "Anjuna Flea Market", "categories": ["shopping", "food"], "description": "A Wednesday institution of textiles, trinkets and beach food.", "duration_minutes": 90, "cost": 400, "scene_type": "beach", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "afternoon"},
    {"id": "goa-seafood", "destination_id": "goa", "name": "Beach Shack Seafood Dinner", "categories": ["food", "entertainment"], "description": "Fresh catch, sunset views and live music on the sand.", "duration_minutes": 90, "cost": 700, "scene_type": "beach", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "evening"},
    {"id": "goa-church", "destination_id": "goa", "name": "Basilica of Bom Jesus", "categories": ["history", "spiritual", "photography"], "description": "A UNESCO-listed baroque church in Old Goa.", "duration_minutes": 60, "cost": 0, "scene_type": "heritage", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "morning"},

    # ---------------- Ooty ----------------
    {"id": "oot-lake", "destination_id": "ooty", "name": "Ooty Lake Boating", "categories": ["nature"], "description": "A boat ride on the artificial lake framed by eucalyptus groves.", "duration_minutes": 60, "cost": 150, "scene_type": "hills", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "oot-tea", "destination_id": "ooty", "name": "Tea Estate & Factory Tour", "categories": ["nature", "food"], "description": "Rolling tea gardens with a tasting at a working tea factory.", "duration_minutes": 90, "cost": 200, "scene_type": "hills", "travel_minutes_to_next": 20, "distance_km_to_next": 8, "best_slot": "morning"},
    {"id": "oot-toytrain", "destination_id": "ooty", "name": "Nilgiri Mountain Toy Train", "categories": ["adventure", "photography"], "description": "A UNESCO heritage narrow-gauge railway through pine forests.", "duration_minutes": 180, "cost": 300, "scene_type": "hills", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "oot-botanical", "destination_id": "ooty", "name": "Government Botanical Garden", "categories": ["nature", "photography"], "description": "Terraced Victorian-era gardens with rare tree species.", "duration_minutes": 75, "cost": 50, "scene_type": "hills", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "afternoon"},
    {"id": "oot-market", "destination_id": "ooty", "name": "Charing Cross Market & Chocolates", "categories": ["shopping", "food"], "description": "Homemade Nilgiri chocolate, eucalyptus oil and warm woollens.", "duration_minutes": 60, "cost": 300, "scene_type": "hills", "travel_minutes_to_next": 10, "distance_km_to_next": 3, "best_slot": "evening"},

    # ---------------- Bengaluru ----------------
    {"id": "blr-lalbagh", "destination_id": "bengaluru", "name": "Lalbagh Botanical Garden", "categories": ["nature", "photography"], "description": "240 acres of glasshouse gardens and a rock over 3 billion years old.", "duration_minutes": 90, "cost": 30, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "blr-palace", "destination_id": "bengaluru", "name": "Bangalore Palace", "categories": ["history", "photography"], "description": "A Tudor-style palace built in 1887, complete with fortified towers.", "duration_minutes": 75, "cost": 230, "scene_type": "heritage", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "morning"},
    {"id": "blr-brewery", "destination_id": "bengaluru", "name": "Craft Brewery & Food Trail", "categories": ["food", "entertainment"], "description": "India's craft-beer capital, with brewpubs across Indiranagar and Koramangala.", "duration_minutes": 120, "cost": 800, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},
    {"id": "blr-commercial", "destination_id": "bengaluru", "name": "Commercial Street Shopping", "categories": ["shopping"], "description": "One of the city's oldest and busiest shopping streets.", "duration_minutes": 90, "cost": 500, "scene_type": "city", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "afternoon"},
    {"id": "blr-cubbon", "destination_id": "bengaluru", "name": "Cubbon Park Walk", "categories": ["nature"], "description": "A green, tree-lined escape in the middle of the city.", "duration_minutes": 60, "cost": 0, "scene_type": "city", "travel_minutes_to_next": 10, "distance_km_to_next": 3, "best_slot": "morning"},

    # ---------------- Delhi ----------------
    {"id": "del-redfort", "destination_id": "delhi", "name": "Red Fort", "categories": ["history", "photography"], "description": "The Mughal seat of power for over 200 years.", "duration_minutes": 90, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 4, "best_slot": "morning"},
    {"id": "del-chandnichowk", "destination_id": "delhi", "name": "Chandni Chowk Food Walk", "categories": ["food", "shopping"], "description": "Old Delhi's legendary lanes of parathas, chaat and spice markets.", "duration_minutes": 90, "cost": 350, "scene_type": "city", "travel_minutes_to_next": 20, "distance_km_to_next": 6, "best_slot": "afternoon"},
    {"id": "del-qutub", "destination_id": "delhi", "name": "Qutub Minar", "categories": ["history", "photography"], "description": "A 73m Indo-Islamic tower dating to 1193.", "duration_minutes": 75, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 25, "distance_km_to_next": 9, "best_slot": "afternoon"},
    {"id": "del-humayun", "destination_id": "delhi", "name": "Humayun's Tomb", "categories": ["history", "photography"], "description": "The garden-tomb that inspired the Taj Mahal.", "duration_minutes": 75, "cost": 50, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "del-connaught", "destination_id": "delhi", "name": "Connaught Place", "categories": ["shopping", "entertainment"], "description": "Colonial-era colonnades now full of cafes and flagship stores.", "duration_minutes": 90, "cost": 400, "scene_type": "city", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "evening"},

    # ---------------- Mumbai ----------------
    {"id": "mum-gateway", "destination_id": "mumbai", "name": "Gateway of India & Colaba", "categories": ["history", "photography"], "description": "Mumbai's waterfront arch and its surrounding colonial quarter.", "duration_minutes": 90, "cost": 0, "scene_type": "heritage", "travel_minutes_to_next": 12, "distance_km_to_next": 3, "best_slot": "morning"},
    {"id": "mum-marine", "destination_id": "mumbai", "name": "Marine Drive Sunset Walk", "categories": ["nature", "photography"], "description": "The Queen's Necklace — a sweeping bay-side promenade.", "duration_minutes": 60, "cost": 0, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "evening"},
    {"id": "mum-street-food", "destination_id": "mumbai", "name": "Mohammed Ali Road Food Trail", "categories": ["food"], "description": "Legendary kebabs, kheer and seekh rolls after sunset.", "duration_minutes": 90, "cost": 400, "scene_type": "city", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "evening"},
    {"id": "mum-elephanta", "destination_id": "mumbai", "name": "Elephanta Caves", "categories": ["history", "adventure"], "description": "Rock-cut cave temples on an island, a short ferry ride away.", "duration_minutes": 180, "cost": 250, "scene_type": "heritage", "travel_minutes_to_next": 30, "distance_km_to_next": 10, "best_slot": "morning"},
    {"id": "mum-bandra", "destination_id": "mumbai", "name": "Bandra Street Art & Cafes", "categories": ["shopping", "entertainment", "photography"], "description": "Murals, boutiques and the city's buzziest cafe scene.", "duration_minutes": 90, "cost": 500, "scene_type": "city", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "afternoon"},

    # ---------------- Chennai ----------------
    {"id": "che-kapaleeshwarar", "destination_id": "chennai", "name": "Kapaleeshwarar Temple", "categories": ["spiritual", "history", "photography"], "description": "A vividly painted Dravidian temple in the heart of Mylapore.", "duration_minutes": 75, "cost": 0, "scene_type": "temple", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "che-marina", "destination_id": "chennai", "name": "Marina Beach", "categories": ["nature"], "description": "The world's second-longest urban beach, lively at sunrise and sunset.", "duration_minutes": 90, "cost": 0, "scene_type": "beach", "travel_minutes_to_next": 20, "distance_km_to_next": 7, "best_slot": "evening"},
    {"id": "che-fort", "destination_id": "chennai", "name": "Fort St. George", "categories": ["history"], "description": "The first English fortress in India, built in 1644.", "duration_minutes": 75, "cost": 30, "scene_type": "heritage", "travel_minutes_to_next": 15, "distance_km_to_next": 5, "best_slot": "morning"},
    {"id": "che-food", "destination_id": "chennai", "name": "Mylapore Filter Coffee & Food Trail", "categories": ["food"], "description": "Classic Chennai breakfast — idli, filter coffee and kothu parotta.", "duration_minutes": 60, "cost": 250, "scene_type": "city", "travel_minutes_to_next": 12, "distance_km_to_next": 4, "best_slot": "afternoon"},
]


def get_attractions_for(destination_id: str) -> list[dict]:
    return [a for a in MOCK_ATTRACTIONS if a["destination_id"] == destination_id]


def get_attraction_by_id(attraction_id: str) -> dict | None:
    return next((a for a in MOCK_ATTRACTIONS if a["id"] == attraction_id), None)
